// content.js - Comedy content database
const comedyContent = {
    // Punchlines for Setup Battle round
    punchlines: [
        "...and that's when I realized I was at the wrong funeral.",
        "...but apparently 'trust fall' means something different at a bank.",
        "...turns out 'gluten-free' doesn't mean 'free gluten'.",
        "...and that's how I became banned from every Home Depot in the tri-state area.",
        "...which explains why my GPS now speaks only in disappointed sighs.",
        "...and the TSA agent said, 'Sir, that's not how you use a metal detector.'",
        "...but my therapist says I'm making progress.",
        "...and that's when my mother-in-law finally approved of me.",
        "...turns out 'Netflix and chill' has a very different meaning at the retirement home.",
        "...and the fortune cookie was right: I should have stayed in bed.",
        "...which is why I'm no longer allowed at parent-teacher conferences.",
        "...and that's how I learned that 'organic' doesn't always mean 'edible'.",
        "...but my dog still won't make eye contact with me.",
        "...and the police officer said, 'I've never seen anyone parallel park like that before.'",
        "...turns out my spirit animal is a confused sloth.",
        "...and that's when I realized autocorrect had been writing my love letters.",
        "...but apparently that's not what they meant by 'customer service'.",
        "...and now I know why they call it 'rush hour' traffic.",
        "...which explains the strange looks at the yoga class.",
        "...and the waiter asked if I wanted to speak to a manager... again.",
        "...but my horoscope said this would be a good day.",
        "...and that's how I became the neighborhood's unofficial wildlife control.",
        "...turns out 'farm to table' doesn't include my backyard compost.",
        "...and my Fitbit filed a formal complaint.",
        "...which is why I'm now banned from all karaoke bars in the city.",
        "...and the delivery guy said, 'This is why we have size limits.'",
        "...but my cat judges me more than usual now.",
        "...and that's when I learned that Wi-Fi passwords have feelings too.",
        "...turns out 'artisanal' is just fancy talk for 'overpriced'.",
        "...and the librarian whispered, 'This is a new level of quiet.'",
        "...but my smart home is now dumber than ever.",
        "...and that's how I discovered my true calling as a professional apologizer.",
        "...which explains why my dating profile now lists 'amateur disaster' as a hobby.",
        "...and the dentist said, 'I've never seen teeth express existential dread before.'",
        "...but my plants are still more successful than my social life.",
        "...and that's when I realized my life needed subtitles.",
        "...turns out 'mindfulness' doesn't apply to microwave cooking times.",
        "...and the barista started charging me a 'complexity fee'.",
        "...which is why my mirror and I are no longer on speaking terms.",
        "...and that's how I learned that gravity is not just a suggestion.",
        "...but my refrigerator light bulb still believes in me.",
        "...and the pizza delivery guy now knows me by my existential crisis orders.",
        "...turns out 'life hack' is just another word for 'creative failure'.",
        "...and that's when my houseplants started an intervention.",
        "...which explains why my sock drawer filed for independence.",
        "...and the weather app apologized for my life choices.",
        "...but my coffee maker still starts every morning with hope.",
        "...and that's how I became the unofficial mascot for Murphy's Law.",
        "...turns out 'adulting' is just childhood with taxes and back pain.",
        "...and the self-checkout machine said, 'Please try being human again.'",
        "...and that's when the stripper said, 'That's not where the tip goes!'",
        "...but my blind date thought 'spicy' meant a literal chili-eating contest.",
        "...turns out my 'intimate yoga retreat' was just a sweaty misunderstanding.",
        "...and the bartender said, 'Mate, that's not how you do body shots.'",
        "...which is why my Roomba now moonlights as an adult toy cleaner.",
        "...and that's how I got kicked out of the nudist colony for 'overenthusiasm'.",
        "...but my grandma's 'special brownies' were a bit too special.",
        "...and the neighbor's hot tub party got way out of hand.",
        "...turns out 'open bar' doesn't mean 'open your pants'.",
        "...and that's why my inflatable pool float is now in therapy.",
        "...but the swingers' club thought my disco moves were a bit too literal.",
        "...and the chef said, 'That's not what I meant by tossing the salad!'",
        "...which explains why my vibrator has a better social life than me.",
        "...and that's how I got banned from the pet store's 'adopt a snake' day.",
        "...but my 'erotic poetry' reading turned into a group therapy session.",
        "...and the masseuse said, 'Sir, that's not what a happy ending means.'",
        "...turns out my 'spicy playlist' was just 90s polka remixes.",
        "...and that's why my Tinder bio now says 'professional wardrobe malfunction'.",
        "...but my 'sexy cooking' attempt set off the smoke alarm.",
        "...and the bouncer said, 'Your dance moves are a public safety hazard.'",
        "...which is why my cat now hides my edible underwear stash.",
        "...and that's how I learned 'BYOB' doesn't mean 'bring your own bananas'.",
        "...but my 'tantric meditation' class was just me snoring loudly.",
        "...and the hotel maid said, 'I've seen kinks, but this is a new one.'",
        "...turns out 'pole dancing' and 'pole vaulting' are not interchangeable.",
        "...and that's why my yoga pants filed for a restraining order.",
        "...but my 'wild night out' was just me arguing with a vending machine.",
        "...and the barista said, 'Your latte art request is NSFW.'",
        "...which explains why my goldfish now gives me side-eye.",
        "...and that's how I got stuck in a kiddie pool with too much lube.",
        "...but my 'DIY waxing' attempt is now a viral cautionary tale.",
        "...and the lifeguard said, 'That's not how you skinny dip!'",
        "...turns out 'hot yoga' was just a sauna with extra moaning.",
        "...and that's why my neighbor's Wi-Fi is now password-protected.",
        "...but my 'erotic novel' pitch was just a grocery list gone wrong.",
        "...and the dog trainer said, 'Your puppy's kinks are not my problem.'",
        "...which is why my inflatable doll is now my emergency contact.",
        "...and that's how I got banned from the vegan potluck for 'lewd carrots'.",
        "...but my 'spicy margarita' was just tequila with hot sauce.",
        "...and the Uber driver said, 'Your backseat antics broke my rating.'",
        "...turns out 'friends with benefits' doesn't cover dental insurance.",
        "...and that's why my smart fridge now censors my late-night snacks.",
        "...but my 'sexy costume' was just a onesie with a bad attitude.",
        "...and the pizza guy said, 'I didn't sign up for this roleplay.'",
        "...which explains why my dating app now flags me as 'chaotic energy'.",
        "...and that's how I learned 'bubble bath' isn't a group activity.",
        "...but my 'romantic picnic' was just ants stealing my vibe.",
        "...and the flight attendant said, 'Sir, that's not the mile-high club.'",
        "...turns out 'speed dating' doesn't involve actual running.",
        "...and that's why my mirror now has a 'no judgment' clause.",
        // Mark Normand-inspired punchlines
        "...and the bartender said, 'Buddy, flirting ain't just yelling 'nice rack'!'",
        "...but my date thought 'low-key' meant whispering dirty limericks.",
        "...turns out my 'signature move' is just spilling beer on my crotch.",
        "...and that's why my wingman now screens my Tinder matches for sanity.",
        "...but my pickup line got me a restraining order and a free coffee.",
        "...and the cashier said, 'Sir, condoms aren't a loyalty points program.'",
        "...turns out 'casual dating' means I'm casually bad at it.",
        "...and that's how I learned foreplay isn't just quoting 'The Notebook.'",
        "...but my 'sexy smirk' looks like I’m passing a kidney stone.",
        "...and the bouncer said, 'Your vibe’s more awkward than a wet fart.'",
        "...which is why my online date now comes with a Terms of Service.",
        "...and that's how I got banned from trivia night for 'lewd answers.'",
        "...but my 'romantic gesture' was just a burrito with extra guac.",
        "...and the barista said, 'Your order’s more complicated than your love life.'",
        "...turns out my 'smooth talk' is just stuttering with confidence.",
        "...and that's why my gym selfie is now exhibit A in my therapy sessions.",
        "...but my 'spicy banter' got me blocked by my own mom.",
        "...and the waiter said, 'Sir, 'extra sauce' isn’t a personality trait.'",
        "...which explains why my dating app matches ghost me by the second text.",
        "...and that's how I learned 'open mic' isn't for bedroom confessions.",
        "...but my 'charm' is just sweat and bad puns.",
        "...and the Uber driver said, 'Your life story’s a one-star review.'",
        "...turns out 'friends with benefits' just means I fix their Wi-Fi.",
        "...and that's why my cat’s my only plus-one to weddings.",
        "...but my 'flirty wink' got me reported to HR.",
        "...and the bar crowd booed my attempt at 'sexy karaoke.'",
        "...which is why my mirror now comes with a trigger warning.",
        "...and that's how I got dumped for 'excessive mansplaining.'",
        "...but my 'date night' was just me and a frozen pizza arguing.",
        "...and the bartender said, 'Your tab’s higher than your standards.'",
        "...turns out my 'bedroom eyes' are just allergies acting up.",
        "...and that's why I’m banned from speed dating for 'over-sharing.'",
        "...but my 'cool vibe' is just cargo shorts and regret.",
        "...and that's how I learned 'happy hour' isn't therapy.",
        // Anthony Jeselnik-inspired punchlines
        "...and that's when I realized my blind date was my parole officer.",
        "...but my grandma’s 'special recipe' was just laced with arsenic.",
        "...turns out my 'family reunion' was just a cult initiation.",
        "...and the priest said, 'That’s not what I meant by holy water.'",
        "...which is why my dog’s now in witness protection.",
        "...and that's how I got banned from the morgue’s open house.",
        "...but my 'charity work' was just robbing the donation box.",
        "...and the doctor said, 'Your test results are a hate crime.'",
        "...turns out my 'romantic getaway' was a one-way trip to nowhere.",
        "...and that's why my therapist now charges hazard pay.",
        "...but my 'surprise party' ended with a police raid.",
        "...and the babysitter said, 'Your kid’s scarier than you.'",
        "...which explains why my dating profile lists 'felony enthusiast.'",
        "...and that's how I learned 'safe word' doesn’t stop a SWAT team.",
        "...but my 'sexy tattoo' was just a prison barcode.",
        "...and the judge said, 'Your alibi’s darker than your humor.'",
        "...turns out my 'new kink' was just a restraining order violation.",
        "...and that's why my cat’s now my alibi witness.",
        "...but my 'hot date' ended with a hazmat team cleanup.",
        "...and the bartender said, 'Your drink order’s a war crime.'",
        "...which is why my family reunion now requires a background check.",
        "...and that's how I got excommunicated from the vegan cult.",
        "...but my 'erotic novel' was just a restraining order in prose.",
        "...and the cop said, 'Your strip search was too enthusiastic.'",
        "...turns out my 'life coach' was just a pyramid scheme recruiter.",
        "...and that's why my obituary’s already trending on X.",
        "...but my 'open relationship' was just me getting dumped twice.",
        "...and the nurse said, 'Your blood type’s pure chaos.'",
        "...which is why my Tinder matches come with a warning label.",
        "...and that's how I learned 'roleplay' doesn’t mean 'arsonist.'",
        "...but my 'party trick' got me on a no-fly list.",
        "...and the landlord said, 'Your lease is a crime scene.'",
        "...turns out my 'spiritual awakening' was just a bad trip.",
        "...and that's why my gravestone reads 'He tried.'",
        // Joey Diaz-inspired punchlines
        "...and that's when I snorted a line of hot sauce at 3 a.m., dawg!",
        "...but the strip club bouncer said, 'You’re too wild for this zoo!'",
        "...turns out my 'date night' was just me fighting a raccoon for pizza!",
        "...and that's how I ended up naked in a Denny’s parking lot, bro!",
        "...but my dealer said, 'You’re smoking my profits, you savage!'",
        "...and the bartender said, 'Your tab’s bigger than your balls, Joey!'",
        "...which is why my neighbor’s dog barks in fear when I walk by!",
        "...and that's how I got kicked out of a buffet for 'excessive passion.'",
        "...but my 'life advice' was just yelling at a slot machine!",
        "...and the cop said, 'Your dance moves are a felony, homes!'",
        "...turns out my 'yoga retreat' was just me passed out in a dive bar!",
        "...and that's why my uncle’s still hiding from that Vegas bookie!",
        "...but my 'romantic getaway' was just a motel with roach roommates!",
        "...and the bodega guy said, 'You’re eating my inventory, you beast!'",
        "...which explains why my Tinder date brought a taser, dawg!",
        "...and that's how I got banned from karaoke for screaming 'Freebird!'",
        "...but my 'health kick' was just eating tacos with extra rage!",
        "...and the bouncer said, 'You’re too loud for this planet, bro!'",
        "...turns out my 'spiritual cleanse' was just tequila and regret!",
        "...and that's why my landlord calls me 'Hurricane Joey!'",
        "...but my 'classy date' was just me stealing napkins from Applebee’s!",
        "...and the bartender said, 'Your stories are scarier than my ex!'",
        "...which is why my cat’s got more street cred than me now!",
        "...and that's how I ended up wrestling a clown at a kid’s party!",
        "...but my 'new diet' was just chasing food trucks on foot!",
        "...and the cab driver said, 'Your life’s a movie I don’t wanna star in!'",
        "...turns out my 'night out' was just me yelling at a jukebox!",
        "...and that's why my parole officer’s got my face tattooed on his nightmares!",
        "...but my 'smooth move' was just slipping on whiskey and pride!",
        "...and the diner waitress said, 'You’re eating like it’s your last meal!'",
        "...which is why my gym membership’s now a restraining order!",
        "...and that's how I got banned from the laundromat for 'wild spins!'",
        "...but my 'new hustle' was just selling expired yogurt to hipsters!",
        // New punchlines inspired by Tim Dillon (edgy, satirical, raunchy)
        "...and that's why my HOA thinks I'm running a brothel out of my garage!",
        "...but the influencer said, 'My OnlyFans pays for this yacht, peasant!'",
        "...turns out my 'wellness retreat' was just a pyramid scheme with kombucha!",
        "...and the realtor said, 'This fixer-upper’s only flaw is the meth lab!'",
        "...which is why my neighbor’s Botox face now haunts my nightmares!",
        "...and that's how I got banned from Whole Foods for yelling 'Big Pharma!'",
        "...but my 'charity gala' was just a tax dodge for crypto bros!",
        "...and the barista said, 'Your oat milk latte funds my midlife crisis!'",
        "...turns out my 'open house' was just a swingers' club with better lighting!",
        "...and that's why my dog’s Instagram has more followers than me!",
        "...but my 'minimalist lifestyle' was just me living in a storage unit!",
        "...and the Uber driver said, 'Your Airbnb’s a crime scene, not a rental!'",
        "...which explains why my yoga instructor’s now selling NFTs of her chakras!",
        "...and that's how I got kicked out of a gated community for 'bad vibes!'",
        "...but my 'wellness coach' was just a Peloton with a cocaine problem!",
        "...and the bartender said, 'Your crypto tip crashed my POS system!'",
        "...turns out my 'farm-to-table' dinner was just roadkill with garnish!",
        "...and that's why my therapist’s now pitching a reality show about me!",
        "...but my 'influencer collab' was just me shilling expired protein bars!",
        "...and the cop said, 'Your TikTok dance is a public health crisis!'",
        "...which is why my neighbor’s pool party now requires a non-disclosure!",
        "...and that's how I got banned from the country club for 'excessive truth!'",
        "...but my 'luxury condo' was just a trailer park with better Wi-Fi!",
        "...and the event planner said, 'Your wedding’s too chaotic for Bravo!'",
        "...turns out my 'self-care day' was just me drunk in a Bath & Body Works!",
        "...and that's why my HOA president’s face is on my dartboard!",
        "...but my 'vegan cleanse' was just starvation with a $200 price tag!",
        "...and the delivery guy said, 'Your DoorDash order’s a cry for help!'",
        "...which explains why my LinkedIn now lists 'professional trainwreck!'",
        "...and that's how I got sued by a mommy blogger for 'slanderous shade!'",
        "...but my 'charity run' was just me fleeing a bad Tinder date!",
        "...and the landlord said, 'Your lease is a middle finger to society!'",
        "...turns out my 'spiritual guru' was just a guy selling vape pens!",
        "...and that's why my neighbor’s Tesla now has my face keyed on it!",
        "...but my 'networking event' was just a Ponzi scheme with appetizers!",
        "...and the barista said, 'Your order’s more pretentious than my art degree!'",
        "...which is why my dating app now bans me for 'excessive honesty!'",
        "...and that's how I got kicked out of a wellness expo for yelling 'scam!'",
        "...but my 'luxury vacation' was just a timeshare pitch in a swamp!",
        "...and the influencer said, 'My followers think you’re a federal crime!'",
        "...turns out my 'organic smoothie' was just kale and despair!",
        "...and that's why my HOA meeting now has a SWAT team on speed dial!",
        "...but my 'side hustle' was just selling knockoff Viagra at a flea market!",
        "...and the cop said, 'Your pool float orgy broke three city ordinances!'",
        "...which is why my therapist’s now writing a book called ‘My Worst Client!’",
        "...and that's how I got banned from a vegan cafe for ‘carnivore energy!’",
        "...but my ‘influencer retreat’ was just a cult with better branding!",
        "...and the realtor said, ‘This penthouse comes with a free restraining order!’",
        "...turns out my ‘self-help seminar’ was just a room full of pyramid schemes!",
        "...and that's why my neighbor’s dog now barks in cryptocurrency!",
        "...but my 'gluten-free lifestyle' was just me eating drywall for clout!",
        "...and the bartender said, 'Your tab’s bigger than a Kardashian’s ego!'",
        "...which explains why my yoga class now has a ‘no ranting’ policy!",
        "...and that's how I got blacklisted from a influencer’s yacht party!",
        "...but my 'detox cleanse' was just me sweating in a porta-potty!",
        "...and the delivery guy said, 'Your order’s more chaotic than a Black Friday!'",
        "...turns out my 'gated community' was just a prison with better landscaping!",
        "...and that's why my LinkedIn profile’s now flagged as ‘unhinged!’",
        "...but my 'charity auction' was just me selling my ex’s stuff for spite!",
        "...and the cop said, 'Your barbecue’s a fire hazard and a moral outrage!'",
        "...which is why my neighbor’s Ring camera now has PTSD!",
        "...and that's how I got banned from a dog park for ‘human barking!’",
        "...but my 'wellness app' was just a scam to sell my data to Big Yoga!",
        "...and the barista said, 'Your latte’s more extra than an influencer’s funeral!'",
        "...turns out my 'luxury spa day' was just a kiddie pool with Epsom salts!",
        "...and that's why my HOA’s now suing me for ‘defamation by sarcasm!’",
        "...but my 'networking brunch' was just a MLM pitch with mimosas!",
        "...and the landlord said, 'Your apartment’s a biohazard and a TED Talk!’",
        "...which is why my Tinder bio now says ‘survivor of suburban hell!’",
        "...and that's how I got kicked out of a PTA meeting for ‘too much truth!’",
        "...but my 'organic lifestyle' was just me stealing fruit from my neighbor’s tree!",
        "...and the event planner said, 'Your party’s too wild for reality TV!'",
        "...turns out my 'meditation retreat' was just me napping in a strip mall!",
        "...and that's why my dog’s TikTok account is now a tax write-off!",
        "...but my 'crypto investment' was just me buying Dogecoin from a hobo!",
        "...and the cop said, 'Your block party’s a riot in the legal sense!'",
        "...which is why my therapist’s now charging me for ‘emotional damages!’",
        "...and that's how I got banned from a farmer’s market for ‘yelling facts!’",
        "...but my 'influencer collab' was just me shilling for a vape cartel!",
        "...and the barista said, 'Your order’s a manifesto, not a coffee!’",
        "...turns out my 'wellness journey' was just me drunk in a juice bar!",
        "...and that's why my neighbor’s Alexa now screams my name in terror!",
        "...but my 'charity livestream' was just me ranting for Venmo donations!",
        "...and the realtor said, 'This mansion’s just a money-laundering front!’",
        "...which explains why my yoga mat’s now evidence in a federal case!",
        "...and that's how I got blacklisted from a vegan festival for ‘meat vibes!’",
        "...but my 'luxury gym’ was just a CrossFit cult with better towels!",
        "...and the delivery guy said, 'Your order’s a war crime against taste!’",
        "...turns out my 'self-care routine' was just me yelling at my Roomba!",
        "...and that's why my HOA’s now got a restraining order against my vibe!",
        "...but my 'artisan coffee’ was just instant grounds with a $20 price tag!",
        "...and the cop said, 'Your tailgate party’s a threat to national security!’",
        "...which is why my LinkedIn’s now just a cry for help in bullet points!",
        "...and that's how I got banned from a book club for ‘too much yelling!’",
        "...but my 'detox retreat' was just a weekend in my cousin’s meth lab!",
        "...and the bartender said, 'Your tab’s a bigger scam than crypto!’",
        "...turns out my 'organic farm' was just a backyard with a dream!",
        "...and that's why my neighbor’s kid now calls me ‘the angry prophet!’",
        "...but my 'influencer deal' was just me shilling for a shady vape empire!",

    ],

    // Setups for Punchline Challenge round
    setups: [
        "I went to buy some camouflage pants the other day...",
        "My wife told me to stop singing 'Wonderwall'...",
        "I told my cat a joke about dogs...",
        "I tried to catch some fog earlier...",
        "My friend decided to name his dog 'Five Miles'...",
        "I bought the world's worst thesaurus yesterday...",
        "I used to hate facial hair...",
        "My therapist says I have a preoccupation with vengeance...",
        "I'm reading a book about anti-gravity...",
        "I told my wife she was drawing her eyebrows too high...",
        "I went to a seafood disco last week...",
        "My math teacher called me average...",
        "I tried to sue the airline for losing my luggage...",
        "My friend asked me to help him round up his 37 sheep...",
        "I bought a dog from a blacksmith...",
        "I'm terrified of speed bumps...",
        "My wife accused me of being immature...",
        "I went to the doctor with hearing problems...",
        "My friend said he didn't understand cloning...",
        "I tried to organize a hide and seek tournament...",
        "My wife is really mad at the fact that I have no sense of direction...",
        "I lost my job at the bank...",
        "My friend keeps saying 'cheer up man it could be worse, you could be stuck underground in a hole full of water'...",
        "I hate Russian dolls...",
        "My wife said I should do lunges to stay in shape...",
        "I went to the store to buy some batteries...",
        "My friend told me I was delusional...",
        "I tried to make a belt out of watches...",
        "My doctor told me I'm going deaf...",
        "I went to a restaurant that serves 'breakfast at any time'...",
        "I tried to spice up my love life with a new app...",
        "My neighbor caught me practicing for the twerking contest...",
        "I brought my own snacks to the adult film audition...",
        "My date said she wanted to 'keep it chill'...",
        "I signed up for a tantric workshop at the community center...",
        "My new personal trainer said to focus on my core...",
        "I tried to impress my crush with my karaoke skills...",
        "My therapist suggested I try role-playing to boost confidence...",
        "I went to a speed-dating event with my pet parrot...",
        "My roommate said our apartment needed more 'vibes'...",
        "I thought 'hot yoga' was just a figure of speech...",
        "My boss caught me practicing my OnlyFans pitch...",
        "I tried to set a new personal record for holding my breath...",
        "My date said she was into 'experimental cuisine'...",
        "I joined a book club to meet singles...",
        "My gym buddy said to try a new protein shake recipe...",
        "I thought 'casual Friday' meant something else...",
        "My blind date said she was looking for 'adventure'...",
        "I tried to fix my Wi-Fi with a sensual voice command...",
        "My new diet plan promised quick results...",
        "I went to a costume party dressed as a sexy avocado...",
        "My friend said I should try 'edible art' for date night...",
        "I signed up for a couples' dance class solo...",
        "My barista wrote her number on my coffee cup...",
        "I tried to surprise my partner with a midnight snack...",
        "My landlord said I needed to 'tone down' my parties...",
        "I thought 'open mic night' was for spicy poetry...",
        "My new smart scale started giving me compliments...",
        "I went to a singles mixer with my inflatable date...",
        "My yoga instructor said to 'find my center'...",
        // Mark Normand-inspired setups
        "I tried to hit on someone at the dive bar last night...",
        "My buddy said I should try 'being myself' on a date...",
        "I thought I nailed the job interview until...",
        "I went to a networking event with my worst pickup line...",
        "My mom set me up on a blind date with her friend’s kid...",
        "I tried to order a 'sexy' cocktail at the bar...",
        "I thought I was smooth at the singles mixer until...",
        "My coworker caught me practicing my 'flirty face'...",
        "I signed up for a speed-dating event with no prep...",
        "I tried to impress my date with my trivia skills...",
        "My Tinder match asked for my best 'dad joke'...",
        "I went to a comedy club and got called on stage...",
        "My gym crush saw me attempt a new workout move...",
        "I thought 'casual drinks' meant something else...",
        "I tried to charm the bartender with my small talk...",
        "My date said I should 'loosen up' at the club...",
        "I went to a friend’s wedding with no plus-one...",
        "I tried to flirt at the grocery store checkout...",
        "My boss invited me to a 'team-building' happy hour...",
        "I thought I could handle a spicy wings challenge...",
        // Anthony Jeselnik-inspired setups
        "I went to my cousin’s funeral with a new joke...",
        "My therapist warned me about my dark sense of humor...",
        "I tried to cheer up my friend at the hospital...",
        "My family reunion took a weird turn when...",
        "I got invited to a charity event for orphans...",
        "My parole officer asked about my weekend plans...",
        "I tried to make small talk at the crime scene...",
        "My new neighbor invited me to a 'quiet' party...",
        "I went to a pet adoption event with bad intentions...",
        "My doctor warned me about my risky lifestyle...",
        "I tried to spice up my eulogy at the funeral...",
        "My date asked about my 'darkest secret'...",
        "I went to a support group for compulsive liars...",
        "My boss caught me writing jokes during a meeting...",
        "I tried to impress my date with a ghost story...",
        "My priest asked why I missed confession...",
        "I went to a vegan potluck with a hidden agenda...",
        "My lawyer said my defense was 'too creative'...",
        "I tried to bond with my cellmate over jokes...",
        "My therapist suggested I try 'dark humor' therapy...",
        // Joey Diaz-inspired setups
        "I went to a shady bar in Jersey at 2 a.m....",
        "My uncle took me to a sketchy poker game...",
        "I tried to score some weed from a new guy...",
        "My night out in Vegas got outta control when...",
        "I went to a dive bar with my crazy cousin...",
        "I tried to hustle some cash at the pool hall...",
        "My buddy dragged me to a strip club on a Tuesday...",
        "I thought I could handle a biker bar’s open mic...",
        "My dealer said I owed him a favor...",
        "I went to a family BBQ with too much tequila...",
        "My old cellmate invited me to a 'reunion'...",
        "I tried to crash a high-stakes card game...",
        "My night at the bodega took a wild turn...",
        "I went to a dive bar’s karaoke night hammered...",
        "I tried to impress a stripper with my life story...",
        "My bookie called me at 3 a.m. about my tab...",
        "I went to a greasy spoon diner at midnight...",
        "I tried to sneak into a VIP club with no ID...",
        "My cousin’s bachelor party got way too real...",
        "I went to a shady pawn shop to sell my watch...",
        // New setups inspired by Tim Dillon (edgy, satirical, societal dysfunction)
        "I went to an influencer’s pop-up event in a strip mall...",
        "My neighbor’s HOA meeting got way too intense when...",
        "I tried to pitch my startup to a shady venture capitalist...",
        "My cousin invited me to a 'wellness retreat' in the desert...",
        "I got dragged to a suburban block party from hell...",
        "I tried to sell my old couch on a sketchy app...",
        "My boss invited me to a 'networking cruise' with influencers...",
        "I went to a vegan influencer’s pop-up brunch...",
        "My landlord tried to sell me on a 'luxury' apartment...",
        "I got roped into a crypto bro’s NFT launch party...",
        "I tried to crash a gated community’s wine night...",
        "My friend said I should try a 'detox cleanse' seminar...",
        "I went to a real estate open house with free mimosas...",
        "My neighbor’s kid started a TikTok empire in our garage...",
        "I tried to impress a socialite at a charity gala...",
        "My HOA president caught me breaking the rules...",
        "I went to a 'self-care' workshop with a shady guru...",
        "My date took me to a rooftop party full of influencers...",
        "I tried to flip a house with zero experience...",
        "I got invited to a 'VIP' influencer yoga class...",
        "My cousin’s MLM pitch took a dark turn when...",
        "I went to a dog park with my unhinged neighbor...",
        "My therapist suggested I try a 'manifestation' retreat...",
        "I tried to haggle at a farmer’s market with a Karen...",
        "My friend dragged me to a shady timeshare presentation...",
        "I went to a suburban barbecue with too many Karens...",
        "My realtor showed me a 'dream home' in a sketchy area...",
        "I tried to join a book club run by Instagram moms...",
        "I got suckered into a 'wellness' pyramid scheme...",
        "My neighbor’s Ring camera caught me doing something dumb...",
        "I went to a hipster coffee shop with a $20 latte menu...",
        "My boss invited me to a 'team-building' escape room...",
        "I tried to impress a crypto bro at a networking event...",
        "My landlord said my apartment needed 'more energy'...",
        "I went to a pet influencer’s adoption event...",
        "I tried to pitch my podcast to a shady producer...",
        "I got invited to a 'luxury' rooftop barbecue...",
        "My neighbor’s kid tried to sell me his TikTok merch...",
        "I went to a wellness expo with a cult vibe...",
        "I tried to negotiate rent with my slumlord...",
        "I got dragged to a suburban PTA meeting...",
        "I went to a 'farm-to-table' dinner in a parking lot...",
        "My friend said I should try 'crypto yoga' classes...",
        "I tried to impress a social media star at a club...",
        "My HOA sent me a cease-and-desist for my lawn...",
        "I went to a 'charity run' sponsored by a shady app...",
        "I tried to sell my old phone to a sketchy pawn shop...",
        "My cousin’s influencer wedding got out of control...",
        "I went to a 'detox' juice bar with a $50 menu...",
        "I tried to crash a gated community’s pool party...",
        "My boss invited me to a 'motivational' seminar...",
        "I went to a hipster farmer’s market with no cash...",
        "My neighbor’s dog got more Instagram likes than me...",
        "I tried to join a 'luxury' gym with no budget...",
        "I went to a real estate seminar run by a con artist...",
        "My friend dragged me to a 'spiritual' influencer event...",
        "I tried to haggle with a shady online reseller...",
        "I went to a suburban potluck with a hidden agenda...",
        "I got invited to a 'VIP' influencer product launch...",
        "I tried to impress my date at a crypto conference..."
    ],

    // Topics for Full Joke Creation round
    topics: [
        "Airport Security",
        "Smart Home Devices",
        "Online Dating",
        "Grocery Shopping",
        "Social Media",
        "Exercise Classes",
        "Coffee Shops",
        "Traffic Jams",
        "Video Calls",
        "Self-Checkout Machines",
        "Weather Apps",
        "Food Delivery",
        "Parking",
        "Public Transportation",
        "Technology Support",
        "Family Reunions",
        "Home Improvement",
        "Cooking Shows",
        "Pet Behavior",
        "Streaming Services",
        "Phone Autocorrect",
        "Assembly Instructions",
        "Health Trends",
        "Travel Delays",
        "Password Requirements",
        "Swinger Parties",
        "Spicy Cooking Classes",
        "Nudist Beaches",
        "Erotic Book Clubs",
        "Adult Toy Stores",
        "Kinky Yoga Retreats",
        "Naughty Baking Shows",
        "Risqué Karaoke Nights",
        "Boudoir Photography",
        "Sexy Costume Parties",
        "Tantric Workshops",
        "Speed Dating Disasters",
        "Fetish Conventions",
        "Hot Tub Mishaps",
        "Lingerie Shopping",
        "Blind Date Blunders",
        "Spicy Food Challenges",
        "Burlesque Classes",
        "Erotic Poetry Slams",
        "Sensual Massage Mix-ups",
        "Twerking Competitions",
        "Strip Poker Nights",
        "Naughty Game Shows",
        "Vibrator Tech Support",
        "Risqué Dance Classes",
        // Mark Normand-inspired topics
        "Bad Pickup Lines",
        "Awkward Bar Flirting",
        "Failed Date Nights",
        "Embarrassing Gym Moments",
        "Tinder Mishaps",
        "Drunk Karaoke Fails",
        "Wedding Plus-One Woes",
        "Grocery Store Flirting",
        "Office Party Disasters",
        "Spicy Food Regrets",
        "Trivia Night Blunders",
        "Awkward Family Dinners",
        "Bar Tab Nightmares",
        "Speed Dating Fiascos",
        "Flirting with Baristas",
        "Failed Dance Moves",
        "Job Interview Gaffes",
        // Anthony Jeselnik-inspired topics
        "Funeral Faux Pas",
        "Morbid Family Secrets",
        "Hospital Room Jokes",
        "Creepy Charity Events",
        "Parole Officer Meetings",
        "Crime Scene Small Talk",
        "Dark Therapy Sessions",
        "Vegan Cult Meetings",
        "Prison Bonding Moments",
        "Risky Tattoo Choices",
        "Eulogy Disasters",
        "Taboo Dating Profiles",
        "Shady Support Groups",
        "Morgue Open Houses",
        "Arsonist Roleplay",
        "No-Fly List Adventures",
        "Cult Initiations",
        // Joey Diaz-inspired topics
        "Shady Bar Fights",
        "Vegas Blackout Nights",
        "Strip Club Shenanigans",
        "Bodega Misadventures",
        "Dive Bar Karaoke",
        "Sketchy Poker Games",
        "Tequila-Fueled BBQs",
        "Biker Bar Blunders",
        "Late-Night Diner Chaos",
        "Hustling at Pool Halls",
        "Bookie Debts",
        "Pawn Shop Hustles",
        "Jersey Street Life",
        "Wild Bachelor Parties",
        "Drug Deal Mix-ups",
        "Motel Room Mayhem",
        // New topics inspired by Tim Dillon (edgy, satirical, societal dysfunction)
        "Influencer Pop-Up Scams",
        "HOA Power Trips",
        "Shady Crypto Parties",
        "Suburban Block Party Chaos",
        "Sketchy Real Estate Deals",
        "Overpriced Wellness Retreats",
        "Instagram Dog Drama",
        "Gated Community Scandals",
        "MLM Pitch Nightmares",
        "Pretentious Coffee Shops",
        "Shady Timeshare Pitches",
        "Influencer Wedding Crashes",
        "Botox-Fueled Neighbor Feuds",
        "Crypto Bro Networking",
        "Karen-Filled PTAs",
        "Luxury Gym Cults",
        "Ponzi Scheme Brunches",
        "Suburban Swinger BBQs",
        "TikTok Merch Hustles",
        "Shady Wellness Expos",
        "Overpriced Juice Bars",
        "Influencer Yacht Disasters",
        "Fake Farm-to-Table Dinners",
        "Crypto Yoga Classes",
        "Slumlord Negotiations",
        "Pet Influencer Events",
        "Shady Podcast Pitches",
        "Suburban Karen Showdowns",
        "NFT Launch Parties",
        "Bougie Charity Galas",
        "Ring Camera Scandals",
        "Luxury Trailer Parks",
        "Shady Online Resellers",
        "Influencer Product Launches",
        "Vegan Influencer Brunches",
        "Motivational Seminar Scams",
        "Hipster Farmer’s Markets",
        "Gated Community Pool Parties",
        "Suburban Potluck Disasters",
        "Crypto Conference Hookups",
        "Overpriced Latte Menus",
        "Shady Startup Pitches",
        "Influencer Retreat Cults",
        "Botox Mommy Bloggers",
        "Luxury Apartment Scams",
        "Dog Park TikTok Drama",
        "Shady Charity Runs",
        "Suburban Wine Night Chaos",
        "Fake Organic Farms",
        "Influencer Funeral Crashes",
        "Peloton Cult Workouts"
    ]
};

// Helper function to get random content
function getRandomContent(type, count = 1) {
    const content = comedyContent[type];
    if (!content) return [];
    
    const shuffled = [...content].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}

// Helper function to get unique content for each player
function getUniqueContentForPlayers(type, playerCount) {
    const content = comedyContent[type];
    if (!content || playerCount > content.length) {
        throw new Error(`Not enough ${type} for ${playerCount} players`);
    }
    
    const shuffled = [...content].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, playerCount);
}

module.exports = {
    comedyContent,
    getRandomContent,
    getUniqueContentForPlayers
};