// content.js - Comedy content database
const comedyContent = {
    // Punchlines for Setup Battle round
    punchlines: [
        "...and that's when I realized I was at the wrong funeral.",
        "...but apparently 'trust fall' means something different at a bank.",
        "...turns out 'gluten-free' doesn't mean 'free gluten'.",
        "...and that's how I became banned from every Home Depot in the tri-state area.",
        "...which explains why my GPS now speaks only in disappointed sighs.",
        "...and the TSA agent said, 'Sir, that's not how you use a metal detector.'",
        "...but my therapist says I'm making progress.",
        "...and that's when my mother-in-law finally approved of me.",
        "...turns out 'Netflix and chill' has a very different meaning at the retirement home.",
        "...and the fortune cookie was right: I should have stayed in bed.",
        "...which is why I'm no longer allowed at parent-teacher conferences.",
        "...and that's how I learned that 'organic' doesn't always mean 'edible'.",
        "...but my dog still won't make eye contact with me.",
        "...and the police officer said, 'I've never seen anyone parallel park like that before.'",
        "...turns out my spirit animal is a confused sloth.",
        "...and that's when I realized autocorrect had been writing my love letters.",
        "...but apparently that's not what they meant by 'customer service'.",
        "...and now I know why they call it 'rush hour' traffic.",
        "...which explains the strange looks at the yoga class.",
        "...and the waiter asked if I wanted to speak to a manager... again.",
        "...but my horoscope said this would be a good day.",
        "...and that's how I became the neighborhood's unofficial wildlife control.",
        "...turns out 'farm to table' doesn't include my backyard compost.",
        "...and my Fitbit filed a formal complaint.",
        "...which is why I'm now banned from all karaoke bars in the city.",
        "...and the delivery guy said, 'This is why we have size limits.'",
        "...but my cat judges me more than usual now.",
        "...and that's when I learned that Wi-Fi passwords have feelings too.",
        "...turns out 'artisanal' is just fancy talk for 'overpriced'.",
        "...and the librarian whispered, 'This is a new level of quiet.'",
        "...but my smart home is now dumber than ever.",
        "...and that's how I discovered my true calling as a professional apologizer.",
        "...which explains why my dating profile now lists 'amateur disaster' as a hobby.",
        "...and the dentist said, 'I've never seen teeth express existential dread before.'",
        "...but my plants are still more successful than my social life.",
        "...and that's when I realized my life needed subtitles.",
        "...turns out 'mindfulness' doesn't apply to microwave cooking times.",
        "...and the barista started charging me a 'complexity fee'.",
        "...which is why my mirror and I are no longer on speaking terms.",
        "...and that's how I learned that gravity is not just a suggestion.",
        "...but my refrigerator light bulb still believes in me.",
        "...and the pizza delivery guy now knows me by my existential crisis orders.",
        "...turns out 'life hack' is just another word for 'creative failure'.",
        "...and that's when my houseplants started an intervention.",
        "...which explains why my sock drawer filed for independence.",
        "...and the weather app apologized for my life choices.",
        "...but my coffee maker still starts every morning with hope.",
        "...and that's how I became the unofficial mascot for Murphy's Law.",
        "...turns out 'adulting' is just childhood with taxes and back pain.",
        "...and the self-checkout machine said, 'Please try being human again.'",
        // New punchlines (raunchy, wild, and funny)
        "...and that's when the stripper said, 'That's not where the tip goes!'",
        "...but my blind date thought 'spicy' meant a literal chili-eating contest.",
        "...turns out my 'intimate yoga retreat' was just a sweaty misunderstanding.",
        "...and the bartender said, 'Mate, that's not how you do body shots.'",
        "...which is why my Roomba now moonlights as an adult toy cleaner.",
        "...and that's how I got kicked out of the nudist colony for 'overenthusiasm'.",
        "...but my grandma's 'special brownies' were a bit too special.",
        "...and the neighbor's hot tub party got way out of hand.",
        "...turns out 'open bar' doesn't mean 'open your pants'.",
        "...and that's why my inflatable pool float is now in therapy.",
        "...but the swingers' club thought my disco moves were a bit too literal.",
        "...and the chef said, 'That's not what I meant by tossing the salad!'",
        "...which explains why my vibrator has a better social life than me.",
        "...and that's how I got banned from the pet store's 'adopt a snake' day.",
        "...but my 'erotic poetry' reading turned into a group therapy session.",
        "...and the masseuse said, 'Sir, that's not what a happy ending means.'",
        "...turns out my 'spicy playlist' was just 90s polka remixes.",
        "...and that's why my Tinder bio now says 'professional wardrobe malfunction'.",
        "...but my attempt at 'sexy cooking' set off the smoke alarm.",
        "...and the bouncer said, 'Your dance moves are a public safety hazard.'",
        "...which is why my cat now hides my edible underwear stash.",
        "...and that's how I learned 'BYOB' doesn't mean 'bring your own bananas'.",
        "...but my 'tantric meditation' class was just me snoring loudly.",
        "...and the hotel maid said, 'I've seen kinks, but this is a new one.'",
        "...turns out 'pole dancing' and 'pole vaulting' are not interchangeable.",
        "...and that's why my yoga pants filed for a restraining order.",
        "...but my 'wild night out' was just me arguing with a vending machine.",
        "...and the barista said, 'Your latte art request is NSFW.'",
        "...which explains why my goldfish now gives me side-eye.",
        "...and that's how I got stuck in a kiddie pool with too much lube.",
        "...but my 'DIY waxing' attempt is now a viral cautionary tale.",
        "...and the lifeguard said, 'That's not how you skinny dip!'",
        "...turns out my 'hot yoga' was just a sauna with extra moaning.",
        "...and that's why my neighbor's Wi-Fi is now password-protected.",
        "...but my 'erotic novel' pitch was just a grocery list gone wrong.",
        "...and the dog trainer said, 'Your puppy's kinks are not my problem.'",
        "...which is why my inflatable doll is now my emergency contact.",
        "...and that's how I got banned from the vegan potluck for 'lewd carrots'.",
        "...but my 'spicy margarita' was just tequila with hot sauce.",
        "...and the Uber driver said, 'Your backseat antics broke my rating.'",
        "...turns out 'friends with benefits' doesn't cover dental insurance.",
        "...and that's why my smart fridge now censors my late-night snacks.",
        "...but my 'sexy costume' was just a onesie with a bad attitude.",
        "...and the pizza guy said, 'I didn't sign up for this roleplay.'",
        "...which explains why my dating app now flags me as 'chaotic energy'.",
        "...and that's how I learned 'bubble bath' isn't a group activity.",
        "...but my 'romantic picnic' was just ants stealing my vibe.",
        "...and the flight attendant said, 'Sir, that's not the mile-high club.'",
        "...turns out 'speed dating' doesn't involve actual running.",
        "...and that's why my mirror now has a 'no judgment' clause."
    ],

    // Setups for Punchline Challenge round
    setups: [
        "I went to buy some camouflage pants the other day...",
        "My wife told me to stop singing 'Wonderwall'...",
        "I told my cat a joke about dogs...",
        "I tried to catch some fog earlier...",
        "My friend decided to name his dog 'Five Miles'...",
        "I bought the world's worst thesaurus yesterday...",
        "I used to hate facial hair...",
        "My therapist says I have a preoccupation with vengeance...",
        "I'm reading a book about anti-gravity...",
        "I told my wife she was drawing her eyebrows too high...",
        "I went to a seafood disco last week...",
        "My math teacher called me average...",
        "I tried to sue the airline for losing my luggage...",
        "My friend asked me to help him round up his 37 sheep...",
        "I bought a dog from a blacksmith...",
        "I'm terrified of speed bumps...",
        "My wife accused me of being immature...",
        "I went to the doctor with hearing problems...",
        "My friend said he didn't understand cloning...",
        "I tried to organize a hide and seek tournament...",
        "My wife is really mad at the fact that I have no sense of direction...",
        "I lost my job at the bank...",
        "My friend keeps saying 'cheer up man it could be worse, you could be stuck underground in a hole full of water'...",
        "I hate Russian dolls...",
        "My wife said I should do lunges to stay in shape...",
        "I went to the store to buy some batteries...",
        "My friend told me I was delusional...",
        "I tried to make a belt out of watches...",
        "My doctor told me I'm going deaf...",
        "I went to a restaurant that serves 'breakfast at any time'...",
        // New setups (raunchy, wild, and funny)
        "I tried to spice up my love life with a new app...",
        "My neighbor caught me practicing for the twerking contest...",
        "I brought my own snacks to the adult film audition...",
        "My date said she wanted to 'keep it chill'...",
        "I signed up for a tantric workshop at the community center...",
        "My new personal trainer said to focus on my core...",
        "I tried to impress my crush with my karaoke skills...",
        "My therapist suggested I try role-playing to boost confidence...",
        "I went to a speed-dating event with my pet parrot...",
        "My roommate said our apartment needed more 'vibes'...",
        "I thought 'hot yoga' was just a figure of speech...",
        "My boss caught me practicing my OnlyFans pitch...",
        "I tried to set a new personal record for holding my breath...",
        "My date said she was into 'experimental cuisine'...",
        "I joined a book club to meet singles...",
        "My gym buddy said to try a new protein shake recipe...",
        "I thought 'casual Friday' meant something else...",
        "My blind date said she was looking for 'adventure'...",
        "I tried to fix my Wi-Fi with a sensual voice command...",
        "My new diet plan promised quick results...",
        "I went to a costume party dressed as a sexy avocado...",
        "My friend said I should try 'edible art' for date night...",
        "I signed up for a couples' dance class solo...",
        "My barista wrote her number on my coffee cup...",
        "I tried to surprise my partner with a midnight snack...",
        "My landlord said I needed to 'tone down' my parties...",
        "I thought 'open mic night' was for spicy poetry...",
        "My new smart scale started giving me compliments...",
        "I went to a singles mixer with my inflatable date...",
        "My yoga instructor said to 'find my center'..."
    ],

    // Topics for Full Joke Creation round
    topics: [
        "Airport Security",
        "Smart Home Devices",
        "Online Dating",
        "Grocery Shopping",
        "Social Media",
        "Exercise Classes",
        "Coffee Shops",
        "Traffic Jams",
        "Video Calls",
        "Self-Checkout Machines",
        "Weather Apps",
        "Food Delivery",
        "Parking",
        "Public Transportation",
        "Technology Support",
        "Family Reunions",
        "Home Improvement",
        "Cooking Shows",
        "Pet Behavior",
        "Streaming Services",
        "Phone Autocorrect",
        "Assembly Instructions",
        "Health Trends",
        "Travel Delays",
        "Password Requirements",
        // New topics (raunchy, wild, and funny)
        "Swinger Parties",
        "Spicy Cooking Classes",
        "Nudist Beaches",
        "Erotic Book Clubs",
        "Adult Toy Stores",
        "Kinky Yoga Retreats",
        "Naughty Baking Shows",
        "Risqué Karaoke Nights",
        "Boudoir Photography",
        "Sexy Costume Parties",
        "Tantric Workshops",
        "Speed Dating Disasters",
        "Fetish Conventions",
        "Hot Tub Mishaps",
        "Lingerie Shopping",
        "Blind Date Blunders",
        "Spicy Food Challenges",
        "Burlesque Classes",
        "Erotic Poetry Slams",
        "Sensual Massage Mix-ups",
        "Twerking Competitions",
        "Strip Poker Nights",
        "Naughty Game Shows",
        "Vibrator Tech Support",
        "Risqué Dance Classes"
    ]
};

// Helper function to get random content
function getRandomContent(type, count = 1) {
    const content = comedyContent[type];
    if (!content) return [];
    
    const shuffled = [...content].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}

// Helper function to get unique content for each player
function getUniqueContentForPlayers(type, playerCount) {
    const content = comedyContent[type];
    if (!content || playerCount > content.length) {
        throw new Error(`Not enough ${type} for ${playerCount} players`);
    }
    
    const shuffled = [...content].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, playerCount);
}

module.exports = {
    comedyContent,
    getRandomContent,
    getUniqueContentForPlayers
};